development:
  adapter: postgresql
  database: idea_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: idea_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: idea_production
  pool: 5
  timeout: 5000
